apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      initContainers:
        - name: wait-for-kafka
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z kafka-srv 9092; do
                echo "Waiting for Kafka to be ready...";
                sleep 2;
              done;
              echo "Kafka is ready!";
      containers:
        - name: auth
          image: rustolebayev/auth
          env:
            - name: JWT_ACCESS_SECRET
              value: some-access-secret
            - name: JWT_ACCESS_TTL
              value: '15m'
            - name: JWT_REFRESH_SECRET
              value: some-refresh-secret
            - name: JWT_REFRESH_TTL
              value: '7d'
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - port: 3000
      targetPort: 3000
      name: auth
      protocol: TCP
