apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      initContainers:
        - name: wait-for-kafka
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z kafka-srv 9092; do
                echo "Waiting for Kafka to be ready...";
                sleep 2;
              done;
              echo "Kafka is ready!";
      containers:
        - name: expiration
          image: rustolebayev/expiration
---
apiVersion: v1
kind: Service
metadata:
  name: expiration-srv
spec:
  selector:
    app: expiration
  ports:
    - port: 3000
      targetPort: 3000
      name: expiration
      protocol: TCP
