apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ticketing-route
spec:
  parentRefs:
    - name: ticketing
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/auth
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: auth-srv
          port: 3000
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: client-srv
          port: 3000