apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-depl
  template:
    metadata:
      labels:
        app: kafka-depl
    spec:
      containers:
        - name: kafka-depl
          image: apache/kafka:3.9.0
          env:
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:9092,CONTROLLER://:9093"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://localhost:9092"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@localhost:9093"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: KAFKA_NUM_PARTITIONS
              value: "3"
          ports:
            - containerPort: 9092
            - containerPort: 9093
      volumes:
        - name: kafka-config-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-srv
spec:
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
      protocol: TCP
  selector:
    app: kafka-depl