apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      initContainers:
        - name: wait-for-kafka
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z kafka-srv 9092; do
                echo "Waiting for Kafka to be ready...";
                sleep 2;
              done;
              echo "Kafka is ready!";
      containers:
        - name: payments
          image: rustolebayev/payments
          env:
            - name: DATABASE_PASSWORD
              value: password
            - name: DATABASE_NAME
              value: postgres
            - name: DATABASE_HOST
              value: payments-database-srv
            - name: JWT_ACCESS_SECRET
              value: some-access-secret
            - name: JWT_REFRESH_SECRET
              value: some-refresh-secret
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
spec:
  selector:
    app: payments
  ports:
    - port: 3000
      targetPort: 3000
      name: payments
      protocol: TCP
