apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: rustolebayev/user
          env:
            - name: DATABASE_PASSWORD
              value: password
            - name: SESSION_SECRET
              value: some-session-secret
            - name: DATABASE_NAME
              value: auth
            - name: DATABASE_HOST
              value: auth-database-srv
            - name: JWT_ACCESS_SECRET
              value: some-access-secret
            - name: JWT_REFRESH_SECRET
              value: some-refresh-secret
---
apiVersion: v1
kind: Service
metadata:
  name: user-srv
spec:
  selector:
    app: user
  ports:
    - port: 3000
      targetPort: 3000
      name: user
      protocol: TCP
